version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf

python:
  version: 3.6
  install:
    - requirements:
      - yaml
      - matplotlib
      - recommonmark
      - sphinx
      - breathe
